### ISSUE TITLE
Content Guard prevents you entering a name for a node if it has no fields.

### ISSUE THREAD

**Issue by Wolfkhan66** [thecogworks/Cogworks.ContentGuard#13]
If you have nodes that have no fields and only the node name is used (e.g. for simple multinode tree pickers) then content guard stops you from being able to give the node a name and save it.

You are then forced to add unneeded fields or navigate to the info tab to be able to save nodes.

**Comment by mzajkowski** [comment]
Hi @Wolfkhan66!

Thanks for this report. We've found the same issue recently and we've got a fix for it already 🎉 It's been fixed in https://github.com/thecogworks/Cogworks.ContentGuard/pull/14 and it'll be released on Nuget/Our soon.

If you want to make a quick workaround, you need to change the order of the content app for the Content Guard and it'll be all good. Or... click to the "Info" tab then to change/create the item. But the release is coming...

Thanks again. I'm closing the issue now.

If you'll find anything else not working as expected - please report it.
